services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    command: ["start-dev"]  # Specify the command to start Keycloak in development mode
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=mongodb
    volumes:
      - ./theme:/opt/keycloak/themes
    ports:
      - "8080:8080"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
