version: "3"
services:
  appointmed-web-app:
    container_name: appointmed-web-app
    build:
      context: ./spa
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_KEYCLOAK_URL=${VITE_KEYCLOAK_URL}
        - VITE_GOOGLE_API_KEY=${VITE_GOOGLE_API_KEY}
        - VITE_KEYCLOAK_REALM=${VITE_KEYCLOAK_REALM}
        - VITE_KEYCLOAK_CLIENT_ID=${VITE_KEYCLOAK_CLIENT_ID}
    ports:
      - "80:80"

  appointmed-api: 
    container_name: appointmed-api 
    restart: unless-stopped
    build:
      context: ./api/appointmed
      args:
        - VAULT_TOKEN=${VAULT_DEV_ROOT_TOKEN_ID}
        - VAULT_URL=${VAULT_URL}
        - KEYCLOAK_URL=${KEYCLOAK_URL}
        - KEYCLOAK_APPOINTMED_REALM=${KEYCLOAK_APPOINTMED_REALM}
        - KEYCLOAK_APPOINTMED_CLIENTID=${KEYCLOAK_APPOINTMED_CLIENTID}
        - MONGODB_HOST=${MONGODB_HOST}
        - MONGODB_PORT=${MONGODB_PORT}
        - MONGODB_DATABASE=${MONGODB_DATABASE}
        - SMTP_HOST=${SMTP_HOST}
        - SMTP_PORT=${SMTP_PORT}
        - SMTP_USERNAME=${SMTP_USERNAME}
        - GOOGLE_OAUTH2_CLIENTID=${GOOGLE_OAUTH2_CLIENTID}
    ports:
      - "9080:9080"

  keycloak:
      image: quay.io/keycloak/keycloak:23.0.1
      environment:
        KC_DB: postgres
        KC_PORT: 80
        KC_DB_URL: jdbc:postgresql://postgres-keycloak/${KEYCLOAK_DB_DATABASE}
        KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
        KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
        KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
        KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
        KC_HOSTNAME_STRICT: 'false'
        KC_HOSTNAME_STRICT_HTTPS: 'false'
        KC_METRICS_ENABLED: 'true'
        KC_FEATURES: token-exchange
        KC_HTTP_ENABLED: 'true'
        PROXY_ADDRESS_FORWARDING: 'true'
        KC_HOSTNAME_STRICT_BACKCHANNEL: 'false'
      volumes:
        - ./theme:/opt/keycloak/themes
      command:
        - "start"
        - "--proxy=edge"
        - "--http-port=80"
      container_name: keycloak
      ports:
      - "8080:80"

  postgres-keycloak:
    image: postgres:latest
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_DATABASE}
      POSTGRES_USER: ${KEYCLOAK_DB_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    restart: unless-stopped
    ports:
      - "5432:5432"

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_APPOINTMED_USERNAME=${MONGO_APPOINTMED_USERNAME} 
      - MONGO_APPOINTMED_PASSWORD=${MONGO_APPOINTMED_PASSWORD}   
      - MONGO_APPOINTMED_DATABASE=${MONGODB_DATABASE}
    volumes:
      - "./mongodb/:/docker-entrypoint-initdb.d/"
    command: [--auth]
    ports:
      - "27017:27017"

  vault:
    image: vault:1.13.3
    container_name: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
