spring:
  application:
    name: appointmed
  data:
    mongodb:
      uri: mongodb://localhost:27017/appointmed
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master

keycloak:
  realm: master
  clientId: oauth2-appointmed-spa

jwt:
  auth:
    converter:
      resource-id: oauth2-appointmed-spa
      principal-attribute: preferred_username

app:
  cors:
    allowed-origins: "*"

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 9080
